# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0030_auto_20160503_1059'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0001_initial'),
        ('sky', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyImages',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Skyview',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='testpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='testpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='TestPage',
        ),
    ]
