# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_auto_20160518_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skyview',
            name='body',
        ),
        migrations.RemoveField(
            model_name='skyview',
            name='intro',
        ),
    ]
